/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as PremiumPlusRouteImport } from './routes/premium-plus'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as SluzbyRouteImport } from './routes/sluzby'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumPlusRoute = PremiumPlusRouteImport.update({
  id: '/premium-plus',
  path: '/premium-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyRoute = SluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gdpr': typeof GdprRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/premium-plus': typeof PremiumPlusRoute
  '/reference': typeof ReferenceRoute
  '/sluzby': typeof SluzbyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gdpr': typeof GdprRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/premium-plus': typeof PremiumPlusRoute
  '/reference': typeof ReferenceRoute
  '/sluzby': typeof SluzbyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gdpr': typeof GdprRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/premium-plus': typeof PremiumPlusRoute
  '/reference': typeof ReferenceRoute
  '/sluzby': typeof SluzbyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gdpr'
    | '/kontakt'
    | '/o-nas'
    | '/premium-plus'
    | '/reference'
    | '/sluzby'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gdpr'
    | '/kontakt'
    | '/o-nas'
    | '/premium-plus'
    | '/reference'
    | '/sluzby'
  id:
    | '__root__'
    | '/'
    | '/gdpr'
    | '/kontakt'
    | '/o-nas'
    | '/premium-plus'
    | '/reference'
    | '/sluzby'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GdprRoute: typeof GdprRoute
  KontaktRoute: typeof KontaktRoute
  ONasRoute: typeof ONasRoute
  PremiumPlusRoute: typeof PremiumPlusRoute
  ReferenceRoute: typeof ReferenceRoute
  SluzbyRoute: typeof SluzbyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-plus': {
      id: '/premium-plus'
      path: '/premium-plus'
      fullPath: '/premium-plus'
      preLoaderRoute: typeof PremiumPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby': {
      id: '/sluzby'
      path: '/sluzby'
      fullPath: '/sluzby'
      preLoaderRoute: typeof SluzbyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GdprRoute: GdprRoute,
  KontaktRoute: KontaktRoute,
  ONasRoute: ONasRoute,
  PremiumPlusRoute: PremiumPlusRoute,
  ReferenceRoute: ReferenceRoute,
  SluzbyRoute: SluzbyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
